### ISSUE TITLE
Build.exe doesn't work without webhook.txt

### ISSUE THREAD

**Issue by LazeHa4ker** [doenerium69/doenerium-fixed#2]
work
![image](https://user-images.githubusercontent.com/125828906/222733655-2338aa75-1ab3-4d3b-bd16-ff80cba5559f.png) 

                                                                                                doesnt work
![image](https://user-images.githubusercontent.com/125828906/222733836-7b04c002-c042-4ddc-979d-264c2b1e0cbb.png)

**Comment by doenerium69** [comment]
will fix this later

**Comment by doenerium69** [comment]
fixed
