### ISSUE TITLE
Not working after building with the webhook in the txt file

### ISSUE THREAD

**Issue by donnyboi1234** [doenerium69/doenerium-fixed#3]
Upon implementing the webhook into webhook.txt, and then building it will not execute any recommendations?
![image_2023-03-03_155001804](https://user-images.githubusercontent.com/95443970/222826589-beb877ee-70a4-47f5-a8f6-f71504137e68.png)

**Comment by donnyboi1234** [comment]
Correct it worked just doesnt upload to the webhook

**Comment by dsrgnzzzr** [comment]
Same problem. The build depends on the webhook.txt, otherwise the logs are not sent.

**Comment by doenerium69** [comment]
i am going to push an update later

**Comment by doenerium69** [comment]
fixed
